package config

// Telegram constants
const (
	DefaultBaseUrl  = "https://api.telegram.org"
	APIEndpoint     = "/bot%s/%s"
	APIFileEndpoint = DefaultBaseUrl + "/file/bot%s/%s"
)

// Constant values for Endpoints
const (
	EndpointGetUpdates                        = "getUpdates"
	EndpointSetWebhook                        = "setWebhook"
	EndpointDeleteWebhook                     = "deleteWebhook"
	EndpointGetWebhook                        = "getWebhookInfo"
	EndpointGetMe                             = "getMe"
	EndpointLogOut                            = "logOut"
	EndpointClose                             = "close"
	EndpointSendMessage                       = "sendMessage"
	EndpointForwardMessage                    = "forwardMessage"
	EndpointForwardMessages                   = "forwardMessages"
	EndpointCopyMessage                       = "copyMessage"
	EndpointCopyMessages                      = "copyMessages"
	EndpointSendPhoto                         = "sendPhoto"
	EndpointSendAudio                         = "sendAudio"
	EndpointSendDocument                      = "sendDocument"
	EndpointSendVideo                         = "sendVideo"
	EndpointSendAnimation                     = "sendAnimation"
	EndpointSendVoice                         = "sendVoice"
	EndpointSendVideoNote                     = "sendVideoNote"
	EndpointSendMediaGroup                    = "sendMediaGroup"
	EndpointSendLocation                      = "sendLocation"
	EndpointEditMessageLiveLocation           = "editMessageLiveLocation"
	EndpointStopMessageLiveLocation           = "stopMessageLiveLocation"
	EndpointSendVenue                         = "sendVenue"
	EndpointSendContact                       = "sendContact"
	EndpointSendPoll                          = "sendPoll"
	EndpointSendDice                          = "sendDice"
	EndpointSendChatAction                    = "sendChatAction"
	EndpointSetMessageReaction                = "setMessageReaction"
	EndpointGetUserProfilePhotos              = "getUserProfilePhotos"
	EndpointGetFile                           = "getFile"
	EndpointBanChatMember                     = "banChatMember"
	EndpointUnbanChatMember                   = "unbanChatMember"
	EndpointRestrictChatMember                = "restrictChatMember"
	EndpointPromoteChatMember                 = "promoteChatMember"
	EndpointSetChatAdministratorCustomTitle   = "setChatAdministratorCustomTitle"
	EndpointBanChatSenderChat                 = "banChatSenderChat"
	EndpointUnbanChatSenderChat               = "unbanChatSenderChat"
	EndpointSetChatPermissions                = "setChatPermissions"
	EndpointExportChatInviteLink              = "exportChatInviteLink"
	EndpointCreateChatInviteLink              = "createChatInviteLink"
	EndpointEditChatInviteLink                = "editChatInviteLink"
	EndpointRevokeChatInviteLink              = "revokeChatInviteLink"
	EndpointApproveChatJoinRequest            = "approveChatJoinRequest"
	EndpointDeclineChatJoinRequest            = "declineChatJoinRequest"
	EndpointSetChatPhoto                      = "setChatPhoto"
	EndpointDeleteChatPhoto                   = "deleteChatPhoto"
	EndpointSetChatTitle                      = "setChatTitle"
	EndpointSetChatDescription                = "setChatDescription"
	EndpointPinChatMessage                    = "pinChatMessage"
	EndpointUnpinChatMessage                  = "unpinChatMessage"
	EndpointUnpinAllChatMessages              = "unpinAllChatMessages"
	EndpointLeaveChat                         = "leaveChat"
	EndpointGetChat                           = "getChat"
	EndpointGetChatAdministrators             = "getChatAdministrators"
	EndpointGetChatMemberCount                = "getChatMemberCount"
	EndpointGetChatMember                     = "getChatMember"
	EndpointSetChatStickerSet                 = "setChatStickerSet"
	EndpointDeleteChatStickerSet              = "deleteChatStickerSet"
	EndpointCreateForumTopic                  = "createForumTopic"
	EndpointEditForumTopic                    = "editForumTopic"
	EndpointCloseForumTopic                   = "closeForumTopic"
	EndpointReopenForumTopic                  = "reopenForumTopic"
	EndpointDeleteForumTopic                  = "deleteForumTopic"
	EndpointUnpinAllForumTopicMessages        = "unpinAllForumTopicMessages"
	EndpointEditGeneralForumTopic             = "editGeneralForumTopic"
	EndpointCloseGeneralForumTopic            = "closeGeneralForumTopic"
	EndpointReopenGeneralForumTopic           = "reopenGeneralForumTopic"
	EndpointHideGeneralForumTopic             = "hideGeneralForumTopic"
	EndpointUnHideGeneralForumTopic           = "unhideGeneralForumTopic"
	EndpointUnpinAllGeneralForumTopicMessages = "unpinAllGeneralForumTopicMessages"
	EndpointGetForumTopicIconStickers         = "getForumTopicIconStickers"
	EndpointAnswerCallbackQuery               = "answerCallbackQuery"
	EndpointGetUserChatBoosts                 = "getUserChatBoosts"
	EndpointGetBusinessConnection             = "getBusinessConnection"
	EndpointSetMyCommands                     = "setMyCommands"
	EndpointDeleteMyCommands                  = "deleteMyCommands"
	EndpointGetMyCommands                     = "getMyCommands"
	EndpointSetMyName                         = "setMyName"
	EndpointGetMyName                         = "getMyName"
	EndpointSetMyDescription                  = "setMyDescription"
	EndpointGetMyDescription                  = "getMyDescription"
	EndpointSetMyShortDescription             = "setMyShortDescription"
	EndpointGetMyShortDescription             = "getMyShortDescription"
	EndpointSetChatMenuButton                 = "setChatMenuButton"
	EndpointGetChatMenuButton                 = "getChatMenuButton"
	EndpointSetMyDefaultAdministratorRights   = "setMyDefaultAdministratorRights"
	EndpointGetMyDefaultAdministratorRights   = "getMyDefaultAdministratorRights"
	EndpointEditMessageText                   = "editMessageText"
	EndpointEditMessageCaption                = "editMessageCaption"
	EndpointEditMessageMedia                  = "editMessageMedia"
	EndpointEditMessageReplyMarkup            = "editMessageReplyMarkup"
	EndpointStopPoll                          = "stopPoll"
	EndpointDeleteMessage                     = "deleteMessage"
	EndpointDeleteMessages                    = "deleteMessages"
	EndpointSendSticker                       = "sendSticker"
	EndpointGetStickerSet                     = "getStickerSet"
	EndpointGetCustomEmojiStickers            = "getCustomEmojiStickers"
	EndpointUploadStickerFile                 = "uploadStickerFile"
	EndpointCreateNewStickerSet               = "createNewStickerSet"
	EndpointAddStickerToSet                   = "addStickerToSet"
	EndpointSetStickerPositionInSet           = "setStickerPositionInSet"
	EndpointDeleteStickerFromSet              = "deleteStickerFromSet"
	EndpointReplaceStickerInSet               = "replaceStickerInSet"
	EndpointSetStickerEmojiList               = "setStickerEmojiList"
	EndpointSetStickerKeywords                = "setStickerKeywords"
	EndpointSetStickerMaskPosition            = "setStickerMaskPosition"
	EndpointSetStickerSetTitle                = "setStickerSetTitle"
	EndpointSetStickerSetThumbnail            = "setStickerSetThumbnail"
	EndpointSetCustomEmojiStickerSetThumbnail = "setCustomEmojiStickerSetThumbnail"
	EndpointDeleteStickerSet                  = "deleteStickerSet"
	EndpointAnswerInlineQuery                 = "answerInlineQuery"
	EndpointAnswerWebAppQuery                 = "answerWebAppQuery"
	EndpointSendInvoice                       = "sendInvoice"
	EndpointCreateInvoiceLink                 = "createInvoiceLink"
	EndpointAnswerShippingQuery               = "answerShippingQuery"
	EndpointAnswerPreCheckoutQuery            = "answerPreCheckoutQuery"
	EndpointSetPassportDataErrors             = "setPassportDataErrors"
	EndpointSendGame                          = "sendGame"
	EndpointSetGameScore                      = "setGameScore"
	EndpointGetGameHighScores                 = "getGameHighScores"
)

// Constant values for ChatActions
const (
	ChatTyping          = "typing"
	ChatUploadPhoto     = "upload_photo"
	ChatRecordVideo     = "record_video"
	ChatUploadVideo     = "upload_video"
	ChatRecordVoice     = "record_voice"
	ChatUploadVoice     = "upload_voice"
	ChatUploadDocument  = "upload_document"
	ChatChooseSticker   = "choose_sticker"
	ChatFindLocation    = "find_location"
	ChatRecordVideoNote = "record_video_note"
	ChatUploadVideoNote = "upload_video_note"
)

// Constant values for ParseMode in MessageConfig
const (
	ModeMarkdown   = "Markdown"
	ModeMarkdownV2 = "MarkdownV2"
	ModeHTML       = "HTML"
)
