package config

// Telegram constants
const (
	DefaultBaseUrl  = "https://api.telegram.org"
	APIEndpoint     = "/bot%s/%s"
	APIFileEndpoint = "/file/bot%s/%s"
)

// Constant values for Endpoints
const (
	EndpointGetUpdates                      = "getUpdates"
	EndpointSetWebhook                      = "setWebhook"
	EndpointDeleteWebhook                   = "deleteWebhook"
	EndpointGetWebhook                      = "getWebhookInfo"
	EndpointGetMe                           = "getMe"
	EndpointLogOut                          = "logOut"
	EndpointClose                           = "close"
	EndpointSendMessage                     = "sendMessage"
	EndpointForwardMessage                  = "forwardMessage"
	EndpointCopyMessage                     = "copyMessage"
	EndpointSendPhoto                       = "sendPhoto"
	EndpointSendAudio                       = "sendAudio"
	EndpointSendDocument                    = "sendDocument"
	EndpointSendVideo                       = "sendVideo"
	EndpointSendAnimation                   = "sendAnimation"
	EndpointSendVoice                       = "sendVoice"
	EndpointSendVideoNote                   = "sendVideoNote"
	EndpointSendMediaGroup                  = "sendMediaGroup"
	EndpointSendLocation                    = "sendLocation"
	EndpointEditMessageLiveLocation         = "editMessageLiveLocation"
	EndpointStopMessageLiveLocation         = "stopMessageLiveLocation"
	EndpointSendVenue                       = "sendVenue"
	EndpointSendContact                     = "sendContact"
	EndpointSendPoll                        = "sendPoll"
	EndpointSendDice                        = "sendDice"
	EndpointSendChatAction                  = "sendChatAction"
	EndpointGetUserProfilePhotos            = "getUserProfilePhotos"
	EndpointGetFile                         = "getFile"
	EndpointBanChatMember                   = "banChatMember"
	EndpointUnbanChatMember                 = "unbanChatMember"
	EndpointRestrictChatMember              = "restrictChatMember"
	EndpointPromoteChatMember               = "promoteChatMember"
	EndpointSetChatAdministratorCustomTitle = "setChatAdministratorCustomTitle"
	EndpointBanChatSenderChat               = "banChatSenderChat"
	EndpointUnbanChatSenderChat             = "unbanChatSenderChat"
	EndpointSetChatPermissions              = "setChatPermissions"
	EndpointExportChatInviteLink            = "exportChatInviteLink"
	EndpointCreateChatInviteLink            = "createChatInviteLink"
	EndpointEditChatInviteLink              = "editChatInviteLink"
	EndpointRevokeChatInviteLink            = "revokeChatInviteLink"
	EndpointApproveChatJoinRequest          = "approveChatJoinRequest"
	EndpointDeclineChatJoinRequest          = "declineChatJoinRequest"
	EndpointSetChatPhoto                    = "setChatPhoto"
	EndpointDeleteChatPhoto                 = "deleteChatPhoto"
	EndpointSetChatTitle                    = "setChatTitle"
	EndpointSetChatDescription              = "setChatDescription"
	EndpointPinChatMessage                  = "pinChatMessage"
	EndpointUnpinChatMessage                = "unpinChatMessage"
	EndpointUnpinAllChatMessages            = "unpinAllChatMessages"
	EndpointLeaveChat                       = "leaveChat"
	EndpointGetChat                         = "getChat"
	EndpointGetChatAdministrators           = "getChatAdministrators"
	EndpointGetChatMemberCount              = "getChatMemberCount"
	EndpointGetChatMember                   = "getChatMember"
	EndpointSetChatStickerSet               = "setChatStickerSet"
	EndpointDeleteChatStickerSet            = "deleteChatStickerSet"
	EndpointAnswerCallbackQuery             = "answerCallbackQuery"
	EndpointSetMyCommands                   = "setMyCommands"
	EndpointDeleteMyCommands                = "deleteMyCommands"
	EndpointGetMyCommands                   = "getMyCommands"
	EndpointSetChatMenuButton               = "setChatMenuButton"
	EndpointGetChatMenuButton               = "getChatMenuButton"
	EndpointSetMyDefaultAdministratorRights = "setMyDefaultAdministratorRights"
	EndpointGetMyDefaultAdministratorRights = "getMyDefaultAdministratorRights"
	EndpointEditMessageText                 = "editMessageText"
	EndpointEditMessageCaption              = "editMessageCaption"
	EndpointEditMessageMedia                = "editMessageMedia"
	EndpointEditMessageReplyMarkup          = "editMessageReplyMarkup"
	EndpointStopPoll                        = "stopPoll"
	EndpointDeleteMessage                   = "deleteMessage"
	EndpointSendSticker                     = "sendSticker"
	EndpointGetStickerSet                   = "getStickerSet"
	EndpointGetCustomEmojiStickers          = "getCustomEmojiStickers"
	EndpointUploadStickerFile               = "uploadStickerFile"
	EndpointCreateNewStickerSet             = "createNewStickerSet"
	EndpointAddStickerToSet                 = "addStickerToSet"
	EndpointSetStickerPositionInSet         = "setStickerPositionInSet"
	EndpointDeleteStickerFromSet            = "deleteStickerFromSet"
	EndpointSetStickerSetThumb              = "setStickerSetThumb"
	EndpointAnswerInlineQuery               = "answerInlineQuery"
	EndpointAnswerWebAppQuery               = "answerWebAppQuery"
	EndpointSendInvoice                     = "sendInvoice"
	EndpointCreateInvoiceLink               = "createInvoiceLink"
	EndpointAnswerShippingQuery             = "answerShippingQuery"
	EndpointAnswerPreCheckoutQuery          = "answerPreCheckoutQuery"
	EndpointSetPassportDataErrors           = "setPassportDataErrors"
	EndpointSendGame                        = "sendGame"
	EndpointSetGameScore                    = "setGameScore"
	EndpointGetGameHighScores               = "getGameHighScores"
)

// Constant values for ChatActions
const (
	ChatTyping          = "typing"
	ChatUploadPhoto     = "upload_photo"
	ChatRecordVideo     = "record_video"
	ChatUploadVideo     = "upload_video"
	ChatRecordVoice     = "record_voice"
	ChatUploadVoice     = "upload_voice"
	ChatUploadDocument  = "upload_document"
	ChatChooseSticker   = "choose_sticker"
	ChatFindLocation    = "find_location"
	ChatRecordVideoNote = "record_video_note"
	ChatUploadVideoNote = "upload_video_note"
)

// Constant values for ParseMode in MessageConfig
const (
	ModeMarkdown   = "Markdown"
	ModeMarkdownV2 = "MarkdownV2"
	ModeHTML       = "HTML"
)
